name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notify_init:
    runs-on: ubuntu-latest
    steps:
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - name: Discord notification PR
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: >
          <:kolibri:790471932025372693> [[{{ SHORT_SHA }}](https://github.com/{{ GITHUB_REPOSITORY }}/commit/{{ SHORT_SHA }})] [Starting Kolibri build...](https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}?check_suite_focus=true)
          ```${{ github.event.head_commit.message }}```

  build_and_test_smart_contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - name: "Install SmartPy"
      run: |
        curl -s https://smartpy.io/releases/20201222-65067da80037a151c726ae887cc2a24d02eca2b0/cli/install.sh | sh -s -- local-install ~/smartpy-cli
    - name: "Build and Test Smart Contracts"
      run: |
        cd smart_contracts
        ./compile.sh

  lint_and_build_deploy_scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: "Install Dependencies"
      run: |
        sudo apt-get update && sudo apt-get install build-essential git libusb-1.0-0 libusb-1.0-0-dev libudev-dev
    - name: "Build and lint deploy scripts"
      run: |
        cd deploy
        npm i
        npm run lint
        npm run build

  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: "Build & Deploy Frontend"
      run: |
        cd vue-frontend
        npm i --legacy-peer-deps
        npm run build

    - uses: cloudflare/wrangler-action@1.2.0
      if: github.ref == 'refs/heads/master' # Only deploy on merge to master
      env:
        USER: root
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: 'vue-frontend'
        environment: 'testnet'

    - uses: cloudflare/wrangler-action@1.2.0
      if: github.ref == 'refs/heads/master' # Only deploy on merge to master
      env:
        USER: root
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: 'vue-frontend'
        environment: 'production'

  notify_complete:
    runs-on: ubuntu-latest
    needs:
      - notify_init
      - build_and_test_smart_contracts 
      - lint_and_build_deploy_scripts
      - build_and_deploy_frontend
    steps:
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - name: Discord notification PR
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: >
          <:kolibri:790471932025372693> [[{{ SHORT_SHA }}](https://github.com/{{ GITHUB_REPOSITORY }}/commit/{{ SHORT_SHA }})] [Kolibri built successfully!](https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}?check_suite_focus=true)
          ```${{ github.event.head_commit.message }}```
